db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/polideportivo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
db.usuario=polideportivo_user
db.password=poli1234